---
title: "Node shuffling"
author: "Y"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r knitr_init, echo=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, echo=FALSE, warning=F, message=FALSE}
set.seed(123)
options(stringsAsFactors = FALSE)
options(connectionObserver = NULL)

library(magrittr)
library(clusterProfiler)
library(org.Dm.eg.db)
keytypes(org.Dm.eg.db)
```

```{r}
res.comp.litBM<-read.delim("./input_example/litBM_pairs_rmSelfLoop.txt")


###node shuffling
outputDir="./output_lit_random_NS/"

if(!dir.exists(outputDir)){
  dir.create(outputDir)
}

all.edges<-res.comp.litBM[,1:2]
sampnum<-1000

all.nodes.names<-unique(c(res.comp.litBM$ENTREZ_ID.1,res.comp.litBM$ENTREZ_ID.2))

for(m in 1:sampnum){

  left.nodes<-all.nodes.names
  left.nodes %>% unique()

  nodes.edges<-all.edges

  # setdiff(left.nodes,c(nodes.edges$ENTREZ_ID.1,nodes.edges$ENTREZ_ID.2) %>% unique())

  sub.df<-data.frame()
  for(i in 1:length(all.nodes.names)) {

    tmp <- all.nodes.names[i]
    tmp

    sub.nodes<-sample(setdiff(left.nodes,tmp),1,replace = F)
    sub.nodes

    sub.df[i,1]<-tmp
    sub.df[i,2]<-sub.nodes

    left.nodes<-setdiff(left.nodes,sub.nodes)
    left.nodes


    nodes.edges[nodes.edges==tmp] <- paste(sub.nodes,"ImAsub",sep = "_")

    # setdiff(sub.nodes,left.nodes)

  }
  nodes.edges.sub<-nodes.edges

  nodes.edges$ENTREZ_ID.1 <- gsub("_ImAsub", "", nodes.edges$ENTREZ_ID.1, fixed = TRUE)
  nodes.edges$ENTREZ_ID.2 <- gsub("_ImAsub", "", nodes.edges$ENTREZ_ID.2, fixed = TRUE)

  # setdiff(all.nodes.names,c(nodes.edges$name1,nodes.edges$name2) %>% unique())

  # edges<-nodes.edges

  for(i in 1:length(nodes.edges$ENTREZ_ID.1)){
    nodes.edges$gene.pairs[i]<-paste(nodes.edges$ENTREZ_ID.1[i],nodes.edges$ENTREZ_ID.2[i],sep = "-")
    nodes.edges$gene.pairs[i]<-strsplit(nodes.edges$gene.pairs[i],split = "-")%>% unlist %>% sort %>% paste(collapse = "-")
  }
  
  write.table(nodes.edges,file = paste(outputDir,"NodeShuffle_network_",m,".txt",sep = ""),sep = "\t", quote = F, row.names = F)
}
```



# Session Info

```{r sessioninfo, message=TRUE}
sessionInfo()
```
